AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    image-link-extractor

    Sample SAM Template for Thundra image-link-extractor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 20


Resources:

    ThundraImageLinkExtractor:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: s3://thundra-deploy-staging-oregon/deployments/image-link-extractor/image-link-extractor-2.0-SNAPSHOT.jar
            Handler: io.thundra.examples.imagelinkextractor.ImageLinkExtractorHandler
            Runtime: java8

            Events:
                HelloWorld:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /hello
                        Method: get
